"""empty message

Revision ID: 12248944c465
Revises: None
Create Date: 2015-01-17 01:03:30.098442

"""

# revision identifiers, used by Alembic.
revision = '12248944c465'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_user', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users_user', sa.Column('criticPublication', sa.String(length=120), nullable=True))
    op.add_column('users_user', sa.Column('isCritc', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_user', 'isCritc')
    op.drop_column('users_user', 'criticPublication')
    op.drop_column('users_user', 'bio')
    ### end Alembic commands ###
