"""empty message

Revision ID: 137367ebe50b
Revises: 4f74740e0156
Create Date: 2015-01-17 02:53:40.051275

"""

# revision identifiers, used by Alembic.
revision = '137367ebe50b'
down_revision = '4f74740e0156'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isCritic', sa.Boolean(), nullable=True))
    op.drop_column('users', 'isCritc')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isCritc', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'isCritic')
    ### end Alembic commands ###
