"""empty message

Revision ID: 15feecbae922
Revises: 248d468bd4ed
Create Date: 2015-01-17 03:02:19.166038

"""

# revision identifiers, used by Alembic.
revision = '15feecbae922'
down_revision = '248d468bd4ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
