"""empty message

Revision ID: 1764cfcc5294
Revises: 4d78be8c902b
Create Date: 2015-01-17 10:08:18.942704

"""

# revision identifiers, used by Alembic.
revision = '1764cfcc5294'
down_revision = '4d78be8c902b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session', sa.String(length=120), nullable=True))
    op.drop_constraint(u'users_name_key', 'users', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'users_name_key', 'users', ['name'])
    op.drop_column('users', 'session')
    ### end Alembic commands ###
