"""empty message

Revision ID: 1c374eda390b
Revises: 549c97c0986b
Create Date: 2015-01-17 16:44:29.844065

"""

# revision identifiers, used by Alembic.
revision = '1c374eda390b'
down_revision = '549c97c0986b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('metacriticScore', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'metacriticScore')
    ### end Alembic commands ###
