"""empty message

Revision ID: 1eb889a858c4
Revises: None
Create Date: 2015-01-17 15:56:57.513638

"""

# revision identifiers, used by Alembic.
revision = '1eb889a858c4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('omdbID', sa.Integer(), nullable=True),
    sa.Column('imdbID', sa.String(length=120), nullable=True),
    sa.Column('Title', sa.String(length=255), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Rating', sa.String(length=255), nullable=True),
    sa.Column('Runtime', sa.String(length=255), nullable=True),
    sa.Column('Genre', sa.String(length=255), nullable=True),
    sa.Column('Released', sa.String(length=255), nullable=True),
    sa.Column('Director', sa.String(length=255), nullable=True),
    sa.Column('Writer', sa.String(length=255), nullable=True),
    sa.Column('Cast', sa.Text(), nullable=True),
    sa.Column('Metacritic', sa.Integer(), nullable=True),
    sa.Column('imdbRating', sa.Float(), nullable=True),
    sa.Column('imdbVotes', sa.Integer(), nullable=True),
    sa.Column('Poster', sa.String(length=510), nullable=True),
    sa.Column('Plot', sa.Text(), nullable=True),
    sa.Column('FullPlot', sa.Text(), nullable=True),
    sa.Column('Language', sa.String(length=255), nullable=True),
    sa.Column('Country', sa.String(length=255), nullable=True),
    sa.Column('Awards', sa.Text(), nullable=True),
    sa.Column('lastUpdated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('isCritic', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('criticPublication', sa.String(length=120), nullable=True),
    sa.Column('session', sa.String(length=120), nullable=True),
    sa.Column('highest_review', sa.Integer(), nullable=True),
    sa.Column('lowest_review', sa.Integer(), nullable=True),
    sa.Column('average_review', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('movieId', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('reviewBody', sa.Text(), nullable=True),
    sa.Column('publicationTitle', sa.String(length=120), nullable=True),
    sa.Column('datePosted', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('users')
    op.drop_table('movies')
    ### end Alembic commands ###
