"""empty message

Revision ID: 1fd38421c1b
Revises: 1764cfcc5294
Create Date: 2015-01-17 10:41:27.174036

"""

# revision identifiers, used by Alembic.
revision = '1fd38421c1b'
down_revision = '1764cfcc5294'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('movieId', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('reviewBody', sa.Text(), nullable=True),
    sa.Column('publicationTitle', sa.String(length=120), nullable=True),
    sa.Column('datePosted', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imdbId', sa.String(length=120), nullable=True),
    sa.Column('movieTitle', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('runtime', sa.String(length=255), nullable=True),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.Column('writer', sa.String(length=255), nullable=True),
    sa.Column('actors', sa.String(length=255), nullable=True),
    sa.Column('rated', sa.String(length=255), nullable=True),
    sa.Column('releaseYear', sa.Integer(), nullable=True),
    sa.Column('releaseDate', sa.String(length=255), nullable=True),
    sa.Column('plot', sa.Text(), nullable=True),
    sa.Column('poster', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('awards', sa.String(length=255), nullable=True),
    sa.Column('metascore', sa.Integer(), nullable=True),
    sa.Column('imdbRating', sa.Integer(), nullable=True),
    sa.Column('imdbVotes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    op.drop_table('reviews')
    ### end Alembic commands ###
