"""empty message

Revision ID: 244d32167bec
Revises: 57815c0aa593
Create Date: 2015-01-17 14:59:22.358811

"""

# revision identifiers, used by Alembic.
revision = '244d32167bec'
down_revision = '57815c0aa593'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
