"""empty message

Revision ID: 248d468bd4ed
Revises: None
Create Date: 2015-01-17 03:01:40.381143

"""

# revision identifiers, used by Alembic.
revision = '248d468bd4ed'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('isCritic', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('criticPublication', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
