"""empty message

Revision ID: 46163ae4a100
Revises: None
Create Date: 2015-01-17 11:03:54.016513

"""

# revision identifiers, used by Alembic.
revision = '46163ae4a100'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imdbId', sa.String(length=120), nullable=True),
    sa.Column('movieTitle', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('runtime', sa.String(length=255), nullable=True),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.Column('writer', sa.String(length=255), nullable=True),
    sa.Column('actors', sa.String(length=255), nullable=True),
    sa.Column('rated', sa.String(length=255), nullable=True),
    sa.Column('releaseYear', sa.Integer(), nullable=True),
    sa.Column('releaseDate', sa.String(length=255), nullable=True),
    sa.Column('plot', sa.Text(), nullable=True),
    sa.Column('poster', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('awards', sa.String(length=255), nullable=True),
    sa.Column('metascore', sa.Integer(), nullable=True),
    sa.Column('imdbRating', sa.Integer(), nullable=True),
    sa.Column('imdbVotes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('movieId', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('reviewBody', sa.Text(), nullable=True),
    sa.Column('publicationTitle', sa.String(length=120), nullable=True),
    sa.Column('datePosted', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('isCritic', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('criticPublication', sa.String(length=120), nullable=True),
    sa.Column('session', sa.String(length=120), nullable=True),
    sa.Column('highest_review', sa.Integer(), nullable=True),
    sa.Column('lowest_review', sa.Integer(), nullable=True),
    sa.Column('average_review', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('reviews')
    op.drop_table('movies')
    ### end Alembic commands ###
