"""empty message

Revision ID: 4d78be8c902b
Revises: 15feecbae922
Create Date: 2015-01-17 09:51:28.588312

"""

# revision identifiers, used by Alembic.
revision = '4d78be8c902b'
down_revision = '15feecbae922'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
