"""empty message

Revision ID: 4f74740e0156
Revises: 12248944c465
Create Date: 2015-01-17 01:07:59.768546

"""

# revision identifiers, used by Alembic.
revision = '4f74740e0156'
down_revision = '12248944c465'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('isCritc', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('criticPublication', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
