"""empty message

Revision ID: 549c97c0986b
Revises: 1eb889a858c4
Create Date: 2015-01-17 16:35:22.838896

"""

# revision identifiers, used by Alembic.
revision = '549c97c0986b'
down_revision = '1eb889a858c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('movies', 'ID')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('ID', sa.INTEGER(), server_default=sa.text(u'nextval(\'"movies_ID_seq"\'::regclass)'), nullable=False))
    op.drop_column('movies', 'id')
    ### end Alembic commands ###
