"""empty message

Revision ID: 57815c0aa593
Revises: 46163ae4a100
Create Date: 2015-01-17 14:58:45.357201

"""

# revision identifiers, used by Alembic.
revision = '57815c0aa593'
down_revision = '46163ae4a100'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('Awards', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('Cast', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('Country', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('Director', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('FullPlot', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('Genre', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('Language', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('Metacritic', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('Plot', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('Poster', sa.String(length=510), nullable=True))
    op.add_column('movies', sa.Column('Rating', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('Released', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('Runtime', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('Title', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('Writer', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('Year', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('imdbID', sa.String(length=120), nullable=True))
    op.add_column('movies', sa.Column('lastUpdated', sa.Date(), nullable=True))
    op.drop_column('movies', 'director')
    op.drop_column('movies', 'rated')
    op.drop_column('movies', 'language')
    op.drop_column('movies', 'plot')
    op.drop_column('movies', 'imdbId')
    op.drop_column('movies', 'writer')
    op.drop_column('movies', 'poster')
    op.drop_column('movies', 'metascore')
    op.drop_column('movies', 'releaseDate')
    op.drop_column('movies', 'actors')
    op.drop_column('movies', 'releaseYear')
    op.drop_column('movies', 'genre')
    op.drop_column('movies', 'awards')
    op.drop_column('movies', 'country')
    op.drop_column('movies', 'movieTitle')
    op.drop_column('movies', 'runtime')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('runtime', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('movieTitle', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('awards', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('genre', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('releaseYear', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('actors', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('releaseDate', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('metascore', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('poster', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('writer', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('imdbId', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('plot', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('language', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('rated', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('director', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('movies', 'lastUpdated')
    op.drop_column('movies', 'imdbID')
    op.drop_column('movies', 'Year')
    op.drop_column('movies', 'Writer')
    op.drop_column('movies', 'Title')
    op.drop_column('movies', 'Runtime')
    op.drop_column('movies', 'Released')
    op.drop_column('movies', 'Rating')
    op.drop_column('movies', 'Poster')
    op.drop_column('movies', 'Plot')
    op.drop_column('movies', 'Metacritic')
    op.drop_column('movies', 'Language')
    op.drop_column('movies', 'Genre')
    op.drop_column('movies', 'FullPlot')
    op.drop_column('movies', 'Director')
    op.drop_column('movies', 'Country')
    op.drop_column('movies', 'Cast')
    op.drop_column('movies', 'Awards')
    ### end Alembic commands ###
