"""empty message

Revision ID: 75b6ac93f9e
Revises: 244d32167bec
Create Date: 2015-01-17 15:12:57.977437

"""

# revision identifiers, used by Alembic.
revision = '75b6ac93f9e'
down_revision = '244d32167bec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('omdbID', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'omdbID')
    ### end Alembic commands ###
