"""empty message

Revision ID: 933295cc7b
Revises: 1c374eda390b
Create Date: 2015-01-17 16:47:55.015130

"""

# revision identifiers, used by Alembic.
revision = '933295cc7b'
down_revision = '1c374eda390b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
